name: Check Plugin Updates

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache checked versions
        uses: actions/cache@v3
        with:
          path: checked_versions_4.json
          key: checked-versions-v5
          restore-keys: |
            checked-versions-

      - name: Install dependencies
        run: npm install

      - name: Run update checker
        run: node check-updates.js
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
