name: Check Plugin Updates

on:
  schedule:
    - cron: '0 14 * * 1'
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache checked versions
        uses: actions/cache@v3
        id: cache-check
        with:
          path: .github/actions/setup-libs-update-detector/checked_versions_1.json
          key: checked-versions-v5-${{ github.run_id }}
          restore-keys: |
            checked-versions-v5

      - name: Install dependencies
        run: npm install --prefix .github/actions/setup-libs-update-detector

      - name: Run update checker
        run: node .github/actions/setup-libs-update-detector/check-updates.js
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Save updated cache
        uses: actions/cache@v3
        with:
          path: .github/actions/setup-libs-update-detector/checked_versions_1.json
          key: checked-versions-v5-${{ github.run_id }}
