name: Check Plugin Updates

on:
  schedule:
    - cron: '0 * * * *' # Запуск щогодини
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Ensure cache file exists
        run: |
          if [ ! -f checked_versions.json ]; then
            echo "{}" > checked_versions.json
          fi

      - name: Cache checked versions
        uses: actions/cache@v3
        with:
          path: checked_versions.json
          key: checked-versions-${{ runner.os }}-v1
          restore-keys: |
            checked-versions-${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Run update checker
        run: node check-updates.js
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
